version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: jackhkmatthews/get-started-node:part2
    environment:
      - DB_HOST=db
    ports:
      - "3000:3000"
    # wait until db container is ready
    depends_on:
      - db
    # makes web container aware of db container name_in_compose:name_in_web
    links:
      - db:db
    # Overrides start command in Dockerfile
    command: sh -c './wait-for db:5432 -- npm start'
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=getstartednode